version: "3"
services:

  vote:
    image: forum-website
    ports:
      - 8081:8081
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

networks:
  backend:

